trigger:
  branches:
    include:
      - main  # ou outro nome da branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerImageName: 'fcg-app'
  dockerTag: 'latest'

steps:
  - checkout: self

  - task: DockerInstaller@0
    displayName: 'Instalar Docker (caso necessário)'
    inputs:
      dockerVersion: 'latest'

  # - task: Docker@2
  #   displayName: 'Build da imagem Docker'
  #   inputs:
  #     containerRegistry: 'DockerHubConnection'  # OU use um Service Connection criado antes
  #     repository: '$(dockerImageName)'
  #     command: 'build'
  #     Dockerfile: '**/Dockerfile'
  #     tags: |
  #       $(dockerTag)

# Opcional: Push para DockerHub ou ACR
#  - task: Docker@2
#    displayName: 'Push da imagem Docker'
#    inputs:
#      containerRegistry: 'DockerHubConnection'
#      repository: '$(dockerImageName)'
#      command: 'push'
#      tags: |
#        $(dockerTag)
