name: Docker Image CD (Manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag da imagem Docker'
        required: true
        default: 'latest'
        type: string
      dockerfile_path:
        description: 'Caminho do Dockerfile'
        required: false
        default: './dockerfile'
        type: string
      build_context:
        description: 'Contexto de build'
        required: false
        default: '.'
        type: string
      push_latest:
        description: 'Também fazer push com tag latest?'
        required: false
        default: false
        type: boolean

env:
  REGISTRY: docker.io
  IMAGE_NAME: hagadashi/fcg

jobs:

  deploy-dockerhub:
    name: Realizando deploy no DuckerHub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ inputs.tag }}
          type=raw,value=latest,enable=${{ inputs.push_latest }}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.build_context }}
        file: ${{ inputs.dockerfile_path }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Image digest
      run: echo "Imagem publicada com tags ${{ steps.meta.outputs.tags }}"
          
